# Generated by Django 4.0.4 on 2022-08-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cvsite',
            new_name='cvelement',
        ),
    ]
