# Generated by Django 4.0.4 on 2022-09-19 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvelement',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cvelement',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
