# Generated by Django 4.0.4 on 2022-09-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_cvelement_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvelement',
            name='descrizione',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='cvelement',
            name='nome',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cvelement',
            name='riassunto',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
